shopciti/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('shopciti_app.urls')),  # Include your app's URL patterns
    path('admin/', admin.site.urls),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopciti_app/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path
from . import views 
from .views import CustomLoginView, payfast_success



urlpatterns = [
#//////////////////////////////////////////////////////////////////
    path('', views.index, name='index'),
    path('shops/', views.shops, name='shops'),
    path('shop-info/<int:user_id>/', views.shop_info, name='shop_info'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('about/', views.about, name='about'),
    path('become-vendor/', views.become_vendor, name='become_vendor'),
    path('blogs-details/', views.blogs_details, name='blogs_details'),
    path('blogs/', views.blogs, name='blogs'),
    path('cart/', views.cart, name='cart'),
    path('clear-cart/', views.clear_cart, name='clear_cart'),
    path('remove-from-cart/', views.remove_from_cart, name='remove_from_cart'),
    path('remove-product/', views.remove_product, name='remove_product'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart-total-quantity/', views.cart_total_quantity, name='cart_total_quantity'),
    path('checkout/', views.checkout, name='checkout'),
    path('payfast-return/', views.payfast_return, name='payfast_return'),
    path('payfast-notify/', views.payfast_notify, name='payfast_notify'),
    path('compaire/', views.compaire, name='compaire'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('create-account/', views.create_account, name='create_account'),
    path('random-create-account/', views.random_create_account, name='random_create_account'),
    path('faq/', views.faq, name='faq'),
    path('flash-sale/', views.flash_sale, name='flash_sale'),
    path('privacy/', views.privacy, name='privacy'),
    path('product-info/<int:product_id>/', views.product_info, name='product_info_without_user'),
    path('product-info/<int:product_id>/<int:user_id>/', views.product_info, name='product_info_with_user'),    path('product-sidebar/', views.product_sidebar, name='product_sidebar'),
    path('seller-sidebar/', views.seller_sidebar, name='seller_sidebar'),
    path('sellers/', views.sellers, name='sellers'),
    path('terms/', views.terms, name='terms'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('random-user-dashboard/', views.random_user_dashboard, name='random_user_dashboard'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('add-product/', views.add_product, name='add_product'),
    path('payfast/success/', payfast_success, name='payfast_success'),

]

shopciti_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver


class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=30, default='')
    last_name = models.CharField(max_length=30, default='')
    about = models.TextField(blank=True, null=True)
    logo = models.ImageField(upload_to='profile_image/', blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField()
    country = models.CharField(max_length=50, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    city = models.CharField(max_length=100, default='South Africa')
    postal_code = models.CharField(max_length=20, default='0000')
    phone = models.CharField(max_length=15, default='')  # Provide a default empty string
    
    is_buyer = models.BooleanField(default=False)


    class Meta:
        app_label = 'shopciti_app'


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
Category.objects.create(name='Hoodie')
Category.objects.create(name='Sweater')
Category.objects.create(name='Pants')
Category.objects.create(name='T.shirt')
Category.objects.create(name='Shirt')
Category.objects.create(name='Hat, cap')



class Size(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
Size.objects.create(name='Small')
Size.objects.create(name='Medium')
Size.objects.create(name='Large')
Size.objects.create(name='Xlarge')
Size.objects.create(name='2XL')



class Product(models.Model):
    name = models.CharField(max_length=100)
    short_description = models.TextField(default='')  # Provide a default empty string
    description = models.TextField()
    image = models.ImageField(upload_to='product_images/')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None, blank=True, null=True)
    on_sale = models.BooleanField(default=False)
    sizes = models.ManyToManyField(Size)
    categories = models.ManyToManyField(Category)

    available = models.PositiveIntegerField(default=True)  # assuming it can't be negative

    def __str__(self):
        return self.name


class RelatedProduct(models.Model):
    main_product = models.ForeignKey(Product, related_name='related_products', on_delete=models.CASCADE)
    related_product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.main_product.name} - {self.related_product.name}"


class ProductVariant(models.Model):
    product = models.ForeignKey(Product, related_name='variants', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product_variant_images/', blank=True, null=True)
    size = models.CharField(max_length=50, blank=True, null=True)
    color = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return f"{self.product.name} - {self.name}"


class AdditionalImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='additional_images')
    image = models.ImageField(upload_to='additional_images/')
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None, blank=True, null=True)

    def __str__(self):
        return f"Additional Image for {self.product.name} by {self.added_by.username}"



class SupportTicket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'Ticket #{self.id} by {self.user.username}'
    

class PaymentMethod(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    card_number = models.CharField(max_length=20)
    card_holder_name = models.CharField(max_length=22)
    expiry_date = models.DateField()
    cvv = models.CharField(max_length=3)
    verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    
    def __str__(self):
        return f"{self.card_holder_name} - {self.card_number[-4:]}"

User = get_user_model()


class VendorApplication(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='vendor_applications')
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    shop_name = models.CharField(max_length=100)
    address = models.TextField()
    agreed_to_terms = models.BooleanField(default=False)

    def __str__(self):
        return f"Vendor Application for {self.user.username}"


@receiver(post_save, sender=User)
def create_cart_for_new_user(sender, instance, created, **kwargs):
    if created:
        Cart.objects.create(user=instance)

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    order_id = models.CharField(max_length=8, blank=True, null=True)


    @property
    def total_quantity(self):
        return sum(item.quantity for item in self.cartitem_set.all())

    @property
    def total_price(self):
        return sum(item.get_total_price() for item in self.cartitem_set.all())
        
class CartItem(models.Model):
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE, default=None)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def get_total_price(self):
        return self.product.price * self.quantity

    def __str__(self):
        return f"{self.quantity} of {self.product.name} in cart"


class Order(models.Model):
    order_id = models.CharField(max_length=20, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_status = models.CharField(max_length=20, default='Pending')

    def __str__(self):
        return f"Order ID: {self.order_id}, User: {self.user.username}, Total Price: {self.total_price}"



class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)


    def __str__(self):
        return f"{self.quantity} x {self.product.name} in Order ID: {self.order.order_id}"


class BillingAddress(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    country = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.first_name} {self.last_name}'s Billing Address"

shopciti_app/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .models import CustomUser, Product, AdditionalImage, SupportTicket, PaymentMethod, BillingAddress, Size, Category
from django import forms
from django.forms import inlineformset_factory


class SellerApplicationForm(forms.Form):
    email = forms.EmailField()
    phone = forms.CharField(max_length=15)
    shop_name = forms.CharField(max_length=100)  # Add the shop_name field
    address = forms.CharField(widget=forms.Textarea)
    agreed_to_terms = forms.BooleanField()

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")


# /////////////////////////////////////////////////////////////////////////////////




class VendorRegistrationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'phone_number', 'country', 'address', 'city', 'postal_code', 'logo', 'password1', 'password2')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

class BuyerRegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'phone_number' , 'email', 'password1', 'password2')




class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].required = True  # Ensure old_password field is required



class ProductForm(forms.ModelForm):

       class Meta:
        model = Product
        fields = ['name', 'description', 'image', 'price', 'on_sale']

        widgets = {
            'on_sale': forms.Select(choices=[(True, 'Yes'), (False, 'No')]),
        }


class AdditionalImageForm(forms.ModelForm):
    class Meta:
        model = AdditionalImage
        fields = ['image']

AdditionalImageFormSet = inlineformset_factory(Product, AdditionalImage, form=AdditionalImageForm, extra=3, max_num=5, can_delete=True)



class SupportTicketForm(forms.ModelForm):
    class Meta:
        model = SupportTicket
        fields = ['first_name', 'email', 'phone_number', 'description']

class PaymentMethodForm(forms.ModelForm):
    class Meta:
        model = PaymentMethod
        fields = ['card_number', 'card_holder_name', 'expiry_date', 'cvv']
        widgets = {
            'expiry_date': forms.DateInput(attrs={'type': 'date'}),
            'cvv': forms.PasswordInput(),
        }

    def clean_card_number(self):
        card_number = self.cleaned_data['card_number']
        # Implement any validation logic for card number if needed
        return card_number


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(
        widget=forms.TextInput(attrs={'type': 'number', 'min': '1', 'value': '1'}),
        min_value=1
    )


class BillingAddressForm(forms.ModelForm):
    class Meta:
        model = BillingAddress
        fields = ['first_name', 'last_name', 'email', 'phone', 'country', 'address', 'city', 'postal_code']

class CheckoutForm(forms.Form):
    full_name = forms.CharField(max_length=100, required=True)
    address = forms.CharField(max_length=200, required=True)
    city = forms.CharField(max_length=100, required=True)
    
    # Payment Information
    card_number = forms.CharField(label='Credit Card Number', max_length=16, required=True)
    cardholder_name = forms.CharField(label='Cardholder Name', max_length=100, required=True)
    expiration_date = forms.CharField(label='Expiration Date (MM/YY)', max_length=5, required=True)
    cvv = forms.CharField(label='CVV', max_length=4, required=True)


class PayFastForm(forms.Form):
    # Define the form fields for PayFast
    merchant_id = forms.CharField(initial='23353254')
    merchant_key = forms.CharField(initial='r7cx2yvt9i7gf')
    return_url = forms.URLField()
    cancel_url = forms.URLField()
    notify_url = forms.URLField()
    email_address = forms.EmailField()
    cell_number = forms.CharField()
    m_payment_id = forms.CharField()
    amount = forms.DecimalField()
    item_name = forms.CharField()

shopciti_app/templates/add_product.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Product</title>
    <!-- Add any necessary CSS or stylesheets here -->
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            padding: 20px;
        }
        
        h1 {
            text-align: center;
            margin-bottom: 30px;
        }
        
        form {
            max-width: 500px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        
        label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
        }
        
        input[type="text"],
        input[type="number"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
        
        textarea {
            height: 100px;
        }
        
        button[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
        }
        
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
        
        .checkbox-options {
            display: flex;
            flex-wrap: wrap;
        }
        
        .checkbox-row {
            display: flex;
            margin-bottom: 10px;
            /* Adjust spacing between rows */
        }
        
        .checkbox-option {
            margin-right: 20px;
            /* Adjust spacing between checkboxes */
        }
    </style>
</head>

<body>
    <h1>Add Product</h1>
    <!-- Add fields for product information -->
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ form.as_p }}

        <label for="id_categories">Categories:</label>
        <select name="categories" id="id_categories" multiple>
            {% for category in categories|slice:":6" %}
            <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>

        <div class="row">
            <div class="checkbox-options">
                {% for size in sizes|slice:5 %}
                <div class="checkbox-row">
                    <div class="checkbox-option">
                        <input type="checkbox" id="size_{{ size.id }}" name="sizes" value="{{ size.id }}">
                        <label for="size_{{ size.id }}">{{ size.name }}</label>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <label for="id_available_quantity">Available Quantity:</label>
        <input type="number" id="id_available_quantity" name="available_quantity" min="1" value="{{ available }}">

        <button type="submit">Submit</button>
    </form>

</body>

</html>

shopciti_app/templates/become_vendor.html
{% extends 'base.html' %} {% load static %} {% block content %}


<body>
    <!--------------- blog-tittle-section---------------->
    <section class="blog about-blog">
        <div class="container">
            <div class="blog-bradcrum">
                <span><a href="index.html">Home</a></span>
                <span class="devider">/</span>
                <span><a href="#">Seller Application</a></span>
            </div>
            <div class="blog-heading about-heading">
                <h1 class="heading">Become A Seller!</h1>
            </div>
        </div>
    </section>
    <!--------------- blog-tittle-section-end---------------->

    <!--------------- seller-application-section---------------->
    <section class="seller-application product footer-padding">
        <div class="container">
            <div class="seller-application-section">
                <div class="row ">
                    <div class="col-lg-7">
                        <div class="row gy-5">
                            <div class="col-lg-12">
                                <div class="seller-information" data-aos="fade-right">
                                    <h5 class="comment-title">Seller Information</h5>
                                    <p class="paragraph">Fill the form below or write us We will help you as soon as possible
                                    </p>
                                    <div class="review-form">
                                        <div class="review-inner-form ">
                                            <div class="review-form-name">
                                                <label for="email" class="form-label">Email Address*</label>
                                                <input type="email" id="email" class="form-control" placeholder="Enter your email address">
                                            </div>
                                            <div class="review-form-name">
                                                <label for="phone" class="form-label">Phone*</label>
                                                <input type="number" id="phone" class="form-control" placeholder="+88013**977957">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="seller-information" data-aos="fade-right">
                                    <h5 class="comment-title">Shop Information</h5>
                                    <p class="paragraph">Fill the form below or write us We will help you as soon as possible
                                    </p>
                                    <div class="review-form">
                                        <div class="review-inner-form ">
                                            <div class="review-form-name">
                                                <label for="name" class="form-label">Shop Name*</label>
                                                <input type="text" id="name" class="form-control" placeholder="Name">
                                            </div>
                                            <div class="review-form-name">
                                                <label for="address" class="form-label">Address*</label>
                                                <input type="text" id="address" class="form-control" placeholder="Address">
                                            </div>
                                            <div class="review-form-name checkbox">
                                                <input type="checkbox">
                                                <label for="address" class="form-label">
                                                    I agree all terms and condition in ShopCiti Marketplace</label>
                                            </div>
                                            <div class="form-btn">
                                                <a href="{% url 'create_account' %}">Create Seller Account</a>
                                                <span class="shop-account">Already have an Account?<a
                                                        href="{% url 'login'  %}">Log
                                                        in</a></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-5">
                        <div class="img-upload-section" data-aos="fade-left">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="logo-wrapper">
                                        <h5 class="comment-title">Update Logo</h5>
                                        <p class="paragraph">Profile of at least Size300x300. Gifs work too.Max 5mb.</p>
                                        <div class="logo-upload">
                                            <img src="assets/images/homepage-one/sallers-cover.png" alt="upload" class="upload-img" id="upload-img">
                                            <div class="input-item upload-input">
                                                <label for="input-file">
                                                    <span>
                                                        <svg width="32" height="32" viewBox="0 0 32 32" fill="none"
                                                            xmlns="http://www.w3.org/2000/svg">
                                                            <path
                                                                d="M16.5147 11.5C17.7284 12.7137 18.9234 13.9087 20.1296 15.115C19.9798 15.2611 19.8187 15.4109 19.6651 15.5683C17.4699 17.7635 15.271 19.9587 13.0758 22.1539C12.9334 22.2962 12.7948 22.4386 12.6524 22.5735C12.6187 22.6034 12.5663 22.6296 12.5213 22.6296C11.3788 22.6334 10.2362 22.6297 9.09365 22.6334C9.01498 22.6334 9 22.6034 9 22.536C9 21.4009 9 20.2621 9.00375 19.1271C9.00375 19.0746 9.02997 19.0109 9.06368 18.9772C10.4123 17.6249 11.7609 16.2763 13.1095 14.9277C14.2295 13.8076 15.3459 12.6913 16.466 11.5712C16.4884 11.5487 16.4997 11.5187 16.5147 11.5Z"
                                                                fill="white"></path>
                                                            <path
                                                                d="M20.9499 14.2904C19.7436 13.0842 18.5449 11.8854 17.3499 10.6904C17.5634 10.4694 17.7844 10.2446 18.0054 10.0199C18.2639 9.76139 18.5261 9.50291 18.7884 9.24443C19.118 8.91852 19.5713 8.91852 19.8972 9.24443C20.7251 10.0611 21.5492 10.8815 22.3771 11.6981C22.6993 12.0165 22.7105 12.4698 22.3996 12.792C21.9238 13.2865 21.4443 13.7772 20.9686 14.2717C20.9648 14.2792 20.9536 14.2867 20.9499 14.2904Z"
                                                                fill="white"></path>
                                                        </svg>
                                                    </span>
                                                </label>
                                                <input type="file" accept="image/jpeg, image/jpg, image/png, image/webp" id="input-file">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="logo-wrapper cover">
                                        <h5 class="comment-title">Update Cover</h5>
                                        <p class="paragraph">Cover of at least Size 1170x920.</p>
                                        <div class="cover-upload logo-upload">
                                            <img src="assets/images/homepage-one/sallers-cover.png" alt="upload" class="cover-img" id="cover-img">
                                            <div class="input-item cover-input">
                                                <label for="cover-file">
                                                    <span>
                                                        <svg width="32" height="32" viewBox="0 0 32 32" fill="none"
                                                            xmlns="http://www.w3.org/2000/svg">
                                                            <path
                                                                d="M16.5147 11.5C17.7284 12.7137 18.9234 13.9087 20.1296 15.115C19.9798 15.2611 19.8187 15.4109 19.6651 15.5683C17.4699 17.7635 15.271 19.9587 13.0758 22.1539C12.9334 22.2962 12.7948 22.4386 12.6524 22.5735C12.6187 22.6034 12.5663 22.6296 12.5213 22.6296C11.3788 22.6334 10.2362 22.6297 9.09365 22.6334C9.01498 22.6334 9 22.6034 9 22.536C9 21.4009 9 20.2621 9.00375 19.1271C9.00375 19.0746 9.02997 19.0109 9.06368 18.9772C10.4123 17.6249 11.7609 16.2763 13.1095 14.9277C14.2295 13.8076 15.3459 12.6913 16.466 11.5712C16.4884 11.5487 16.4997 11.5187 16.5147 11.5Z"
                                                                fill="white"></path>
                                                            <path
                                                                d="M20.9499 14.2904C19.7436 13.0842 18.5449 11.8854 17.3499 10.6904C17.5634 10.4694 17.7844 10.2446 18.0054 10.0199C18.2639 9.76139 18.5261 9.50291 18.7884 9.24443C19.118 8.91852 19.5713 8.91852 19.8972 9.24443C20.7251 10.0611 21.5492 10.8815 22.3771 11.6981C22.6993 12.0165 22.7105 12.4698 22.3996 12.792C21.9238 13.2865 21.4443 13.7772 20.9686 14.2717C20.9648 14.2792 20.9536 14.2867 20.9499 14.2904Z"
                                                                fill="white"></path>
                                                        </svg>
                                                    </span>
                                                </label>
                                                <input type="file" accept="image/jpeg, image/jpg, image/png, image/webp" id="cover-file">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--------------- seller-application-section-end---------------->




</body>

{% endblock %}

shopciti_app/templates/cart.html
{% extends 'base.html' %} {% block content %}
<section class="checkout product footer-padding">
    <div class="container">
        <h1>Your Cart</h1>

        {% if cart_items %}
        <form method="post" action="{% url 'clear_cart' %}">
            {% csrf_token %}
            <input type="hidden" name="clear_cart" value="clear">
            <input type="hidden" name="next" value="{{ request.path }}">
            <button type="submit" class="btn btn-danger">Clear Cart</button>
        </form>
        <table class="table">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Remove</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart_items %}
                <tr>
                    <td>{{ item.product.name }}</td>
                    <!-- Accessing product name through the associated product -->
                    <td>R{{ item.product.price }}</td>
                    <!-- Accessing product price through the associated product -->
                    <td>{{ item.quantity }}</td>
                    <td>R{{ item.get_total_price }}</td>
                    <!-- Assuming get_total_price is a method -->
                    <td>
                        <form method="post" action="{% url 'remove_from_cart' %}">
                            {% csrf_token %}
                            <input type="hidden" name="remove_item" value="remove">
                            <input type="hidden" name="product_id" value="{{ item.product.id }}">
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <button type="submit" class="btn btn-danger">Remove</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
        <p>Total: R{{ total_price }}</p>
        <!-- Ensure order_id is displayed -->
        <a href="{% url 'checkout' %}?order_id={{ order_id }}" class="btn btn-primary">Checkout</a> {% else %}
        <p>Your cart is empty.</p>
        {% endif %} {% endblock %}
    </div>
</section>